# Generated by Django 6.0.2 on 2026-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='custom_name',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
