# Generated by Django 6.0.2 on 2026-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_custom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='custom_name',
            field=models.CharField(max_length=255),
        ),
    ]
