# Generated by Django 6.0.2 on 2026-04-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0003_alter_bookmark_custom_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='favicon',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
